[package]
name = "disksift"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
colored = "3.0.0"
humansize = "2.1.3"
indicatif = "0.18.3"
walkdir = "2.5.0"
